# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: squash_ruby 2.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "squash_ruby_fork".freeze
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Tim Morgan".freeze, "Fluxfederation.com".freeze]
  s.date = "2019-01-08"
  s.description = "This client library records Ruby exceptions to Squash.".freeze
  s.email = "guillaume.lenoir@fluxfederation.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "lib/squash/ruby.rb",
    "lib/squash/ruby/exception_additions.rb",
    "lib/squash_ruby.rb"
  ]
  s.homepage = "https://github.com/gleuh/SquareSquash-ruby".freeze
  s.licenses = ["Apache 2.0".freeze]
  s.summary = "Squash client for Ruby projects".freeze

  s.add_runtime_dependency(%q<json>.freeze, [">= 0"])
  s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
  s.add_development_dependency(%q<fakefs>.freeze, [">= 0"])
  s.add_development_dependency(%q<yard>.freeze, [">= 0"])
  s.add_development_dependency(%q<redcarpet>.freeze, [">= 0"])
  s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
end
